### ISSUE TITLE
Pre-configuration steps

### ISSUE THREAD

**Issue by surjansr** [CybercentreCanada/jupyterlab-sql-editor#53]
I am trying this out for my use case and able to use it when I install it from the running notebook like
```
!pip3 install sparksql-magic
%load_ext sparksql_magic
```
but when I am following the [contributing guide to pre-configure](https://github.com/CybercentreCanada/jupyterlab-sql-editor/blob/main/CONTRIBUTING.md#pre-configure-magics-optional) I am getting errors like ipython_magic module not found. I changed it to python_magic as well but the kernel start up logs always complain about the errors.
```
# pre-load the sparksql magic
c.InteractiveShellApp.extensions = [
    'ipython_magic.trino', 'ipython_magic.sparksql' // unable to find this module in pypi.org
    'python-magic.trino', 'python-magic.sparksql' //changed it to python-magic still getting module not found
]
```

```
//error during kernel startup, kernel launches fine but magic won't work.
[IPKernelApp] Loading IPython extension: storemagic
[IPKernelApp] Loading IPython extension: python_magic.sparksql
[IPKernelApp] WARNING | Error in loading extension: python_magic.sparksql
Check your config files in /app/.ipython/profile_custom
Traceback (most recent call last):
  File "/app/.local/lib/python3.7/site-packages/IPython/core/shellapp.py", line 301, in init_extensions
    self.shell.extension_manager.load_extension(ext)
  File "/app/.local/lib/python3.7/site-packages/IPython/core/extensions.py", line 80, in load_extension
    mod = import_module(module_str)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'python_magic'
```

**Comment by surjansr** [comment]
my bad; I missed the ipython_magic was being referred from the "_jupyterlab-sql-editor_" package itself. The name was bit confusing and I think the steps can also be updated. Using fully qualified path for the extension helped

```
c.InteractiveShellApp.extensions = [
    'jupyterlab_sql_editor.ipython_magic.trino'
]
```
